services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-portfolio
    ports:
      - '3002:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - '5437:8000'
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local
